# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='booking',
        ),
    ]
