# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0002_auto_20191205_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='service',
        ),
        migrations.AlterField(
            model_name='booking',
            name='userprofile',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='mobilapp.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
