# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0002_remove_companyprofile_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilapp.Services'),
        ),
    ]
