# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0003_companyprofile_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='companyprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilapp.CompanyProfile'),
        ),
    ]
