# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0004_auto_20191205_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilapp.Services'),
        ),
    ]
