# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0006_companyprofile_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilapp.Booking'),
        ),
    ]
