# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0008_auto_20191204_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
