# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0010_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='servicename',
        ),
    ]
