# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0011_auto_20191204_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='servicename',
            new_name='name',
        ),
    ]
