# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-05 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0012_auto_20191204_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
